version: '3.9'

services:
  cam1:
    build: ./recorder
    network_mode: host
    environment:
      - NAME=cam1
      - RTSP_URL=rtsp://192.168.4.56:554/stream0
    env_file:
      - .env
    volumes:
      - ${OUT}:/out/
    restart: always

  merge:
    build: ./merger
    env_file:
      - .env
    volumes:
      - ${OUT}:/out/
    restart: always