version: '3.9'

services:
  cam1:
    build: ./recorder
    network_mode: host
    environment:
      - NAME=cam1
      - RTSP_URL=${RTSP_URL}
      - OUT=${OUT}
      - TZ=${TZ}
      - FORMAT=${FORMAT}
      - DURATION=${DURATION}
      - SEGMENT_FORMAT=${SEGMENT_FORMAT}
      - TIMEOUT_BUFFER=${TIMEOUT_BUFFER}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ${OUT}:/out/
    restart: always

  merge:
    build: ./merger
    environment:
      - OUT=${OUT}
      - TZ=${TZ}
      - CLEANUP_SPACE=${CLEANUP_SPACE}
      - CLEANUP_REGEX=${CLEANUP_REGEX}
      - CLEANUP_DIR=${CLEANUP_DIR}
      - EMAIL=${EMAIL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    volumes:
      - ${OUT}:/out/
    restart: always