version: '3.9'

services:
  cam1:
    build: ./recorder
    network_mode: host
    environment:
      - NAME=cam1
      - RTSP_URL=${RTSP_URL}
    env_file:
      - .env
    volumes:
      - ${OUT}:/out/
    restart: always

  merge:
    build: ./merger
    env_file:
      - .env
    volumes:
      - ${OUT}:/out/
    restart: always